<div class="HelloWorld-view" data-conlet-title="${_("conletName")}">
    <div style="font-size: 400%">${_("HelloWorld")} 
        <img class="helloWorldIcon" style='vertical-align: bottom;'
            src="${conletResource('globe.ico')}">
        <!-- World icon from http://apathae.deviantart.com/ -->
    </div>
    <button type="button" class="HelloWorld-toggle ui-button ui-widget ui-corner-all">${_("ToggleWorld")}</button>
</div>