name: Java CI with Gradle

on: [push]

concurrency: 
  group: doc_generation
  cancel-in-progress: false

jobs:
  build:
    strategy:
      matrix:
        java-version: [ '21' ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install graphviz
      run: sudo apt-get install graphviz
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew -Prepo.access.token=${{ secrets.REPO_ACCESS_TOKEN }} stage
